### ISSUE TITLE
Balls (flying)

### ISSUE THREAD

**Issue by Claptar** [Claptar/prog_Binkevich#10]

**Comment by antosha417** [comment]
Ты забыл упомянуть меня здесь, нужно написать @antosha417 в каждом issue которое хочешь чтобы я увидел

**Comment by antosha417** [comment]
Добавь хеш коммита к своему комментарию, я просил в телеграмме об этом, спасибо.

**Comment by Claptar** [comment]
@antosha417

**Comment by antosha417** [comment]
Добавь хеш коммита к своему комментарию, я просил в телеграмме об этом, спасибо.

**Comment by Claptar** [comment]
0f35b0209ba592543544bbe09fb36dd266e01cd
2e51d3f0d447576c1fa707e0db2e96e7f99cd149
eea8901962fb277055d878a850058d6cabea6fea

**Comment by Claptar** [comment]
@antosha417

**Comment by antosha417** [comment]
Программа не работает. Попробуй создать класс шарик нужными полями и функциями.  Плохая идея  пихать в массив всё подряд

**Comment by antosha417** [comment]
Ещё советую тебе добавить логирование в консоль всякой информации для отлавливания багов, будет полезно. Можешь просто печатать её на экран, можешь пользоваться библиотекой [logging](https://docs.python.org/3/library/logging.html)

**Comment by Claptar** [comment]
> Ещё советую тебе добавить логирование в консоль всякой информации для отлавливания багов, будет полезно. Можешь просто печатать её на экран, можешь пользоваться библиотекой [logging](https://docs.python.org/3/library/logging.html)

Спасибо, действительно полезно)

**Comment by Claptar** [comment]
> Программа не работает. Попробуй создать класс шарик нужными полями и функциями. Плохая идея пихать в список всё подряд, так очень легко ошибиться, что ты и сделал

Да, собственно это сейчас и хочу сделать)

**Comment by Claptar** [comment]
@antosha417 Cделал работающую программу. Она называется BallGame_2edition
7557ec1c238d74f89d785e4090b4162a55038ab3
71a28fca6776bf8b4f723a9787f33db8baba929b

**Comment by Claptar** [comment]
@antosha417 Там была проблема с индексом
 ed32fa2a78db346391608a4ba116a807785432e8
Пайчарм ругается на названия переменных, но тут достаточно удобно назвать переменные таким образом. Я на паре уточню по переменным в классах, чтобы их корректно переименовать.

**Comment by antosha417** [comment]
Плохой код, я его не понимаю. 
Перепиши его хорошо или объясни почему так индексы ставишь

**Comment by Claptar** [comment]
А что не так с индексами ? Можешь показать непонятные места, чтобы я потом так в коде не писал ?

**Comment by antosha417** [comment]
Вроде всё норм. Я не хочу чтобы были шарики с нулевой скоростью. У тебя не запускатеся программа.

**Comment by antosha417** [comment]
Пайчарм ругается на твой кодстайл и несоблюдение пеп8, поправь, пожалуйста.

**Comment by antosha417** [comment]
Пока ставлю тебе 08  за задачу, чтобы поднять поправь код.

**Comment by Claptar** [comment]
@antosha417 Поправил пеп
b9a03ab87338fa39b4fcc2eaa5571dcadcf1fa44

**Comment by antosha417** [comment]
давай если ты ещё собираешься работать над программой, то работай, а если нет, то пиши сюда.
Как всё сделаешь -- напиши, я посмотрю. Не нужно каждый коммит тут дублировать

**Comment by antosha417** [comment]
А ещё лучше пиши хорошие комментарии. 
> Поправил пеп
Как я могу догадаться что там и шарики тоже? Наверное нужно 2 коммита.

**Comment by antosha417** [comment]
```python
    while Vx == 0 and Vy == 0:
        Vx = random.randint(-10, 10)
        Vy = random.randint(-10, 10)
```
так писать плохо. У тебя тут бесконечный цикл, ты уверен, что функция `randint` когда нибудь вернёт не ноль? Лучше обработать ноль как-нибудь по-другому. Например если ноль, то от 1 до 10 сгенирировать. Или всегда от 1 до 10 и случайно знак ставить. Придумай что-нибудь или прогугли, посмотри как люди делают

**Comment by Claptar** [comment]
@antosha417 
Исправил генерацию скорости)
3fe62fbd2f952c22ede82abdd682a43f6d5c2ba7

**Comment by antosha417** [comment]
Закрывай
