### ISSUE TITLE
Canon game

### ISSUE THREAD

**Issue by Claptar** [Claptar/prog_Binkevich#11]
Сделал программу, которая рассчитывает упругие столкновения мишеней. В папке OOP. Файл называется Targets.
cf5f7810151699794512e63e1483578692f14736
6b0e1371c4b01a0dc17fcbbce773dc4e38062222
69da267e314839b2655856b353a766da25ea30cd

Сделал пушку, которая нормально стреляет и можно выбирать для неё начальную скорость на скролле (Скооперировались с Мишей Клюкиным). Сделал летающие мишени. В папке OOP, файл canon.
f78521d8ba13944455bc393032f633893f6474b4

**Comment by Claptar** [comment]
c334f84dba64ed4e71385efdeea91a207daafed8

**Comment by antosha417** [comment]
Плохо коммитишь. Сделал одно дело -- закомитил. В следующий раз буду снижать баллы.

**Comment by antosha417** [comment]
Докстринг нужно писать сразу после названия функции или класса. Иначе функция help не будет работать.

**Comment by antosha417** [comment]
в функции  `collide`  ничего не понятно

**Comment by antosha417** [comment]
Что это такое?
```python
class Shell:
    global standard_radius
```

**Comment by Claptar** [comment]
@antosha417 
d993012c15deca2d5a18ec4e35d48e285a064bab
384102d47ede3d8a71dd6f11b8b0586ccf5e704e

**Comment by Claptar** [comment]
> Что это такое?
> 
> ```python
> class Shell:
>     global standard_radius
> ```

На лекции ввели как радиус снаряда, он так и остался

**Comment by antosha417** [comment]
Давай если ты сдаёшь код, то ты можешь мне рассказать для чел нужна каждая строчка? Или буду считать, что списал и не разобрался

**Comment by Claptar** [comment]
@antosha417 Эту часть кода писал Миша. Он через этот радиус задавал размер снарядов : задавал размеры прямоугольника в котором будут отрисовываться снаряды.

**Comment by antosha417** [comment]
Зачем глобальная переменная?

**Comment by Claptar** [comment]
@antosha417 О, хорошо, что спросил, надо не забыть у тебя уточнить по глобальным переменным в функциях. Потому что когда-то он понимает и без объявление глобала, а когда-то нет. А тут ты наверное про то, что сначало было написана глобальная переменная и там же и написано значение. Изначально, когда мы делали, были функции вне класса, где использовалась эта переменная, поэтому и объявили её глобальной. Потом функции исчезли, а это не поправили.

**Comment by antosha417** [comment]
Читай код перед тем как отправить!
Про глобальные переменные - не используй их, в большинстве случаев это не оправданно, только если это не настройки проекта какие-нибудь, или константы . Погугли про глобальные переменные, расскажи, что не понял, я постараюсь объяснить

**Comment by Claptar** [comment]
@antosha417 Хорошо, спасибо 😄

**Comment by Claptar** [comment]
@antosha417, почитал про глобальные переменные. Мне ещё нужно что-то досдать по пушке ?

**Comment by antosha417** [comment]
* Вынеси создание окна и запуск игры в функцию.
* Мне кажется индикатор силы заряда не доработан. 
* функция тик делает сильно больше чем `Считает время нажатия клавиши мыши`
Нужно разбить её на более простые и понятные функции.
* Что такое target_creator? Этим должен заниматься __init__  класса `Target`
* докстринг должен быть сразу после `def`
```python 
def tick():
    global Balls, score, score_text
    """
    Считает время нажатия клавиши мыши
    :return:
    """
```

* > почитал про глобальные переменные

Что прочитал? Почему оставил в коде их? 

Пайчарм ругается на твой кодстайл и несоблюдение пеп8, поправь, пожалуйста.
