### ISSUE TITLE
animation

### ISSUE THREAD

**Issue by Claptar** [Claptar/prog_Binkevich#14]
@antosha417, сделал задание по анимации. Файл лежит в папке animation.

**Comment by Claptar** [comment]
c55e459c1b7f20b44959afc7da6f315fb437f6b9
49ac54be328475ce10f715daa94982df474ebb29
9e15215c6990250fe0ece799215d520260fdeeea

**Comment by antosha417** [comment]
Вынеси создания окна и картошки в функцию.

**Comment by antosha417** [comment]
Пока ставлю тебе  0,6 за задачу, чтобы поднять поправь код.
