### ISSUE TITLE
Graphics

### ISSUE THREAD

**Issue by Claptar** [Claptar/prog_Binkevich#8]

**Comment by Claptar** [comment]
@antosha417

**Comment by antosha417** [comment]
Добавь хеш коммита к своему комментарию, я просил в телеграмме об этом, спасибо.

**Comment by Claptar** [comment]
78214e8e60690e585aa6e9eec3968e2e0fddb898
e49dab6f3fa5f0f64869eb579ce0a02ea53c7334
459a2e13bde139eb3a6eb3f6b8ed11a6fc8caef9
3fe1bb71e4b4487bcfe1c76bf4d24b144c7976f2
@antosha417

**Comment by antosha417** [comment]
прочитай как писать коментарии в питоне. И что такое докстринг. Как разберёшься напиши кратко сюда

**Comment by antosha417** [comment]
Давай хорошо подумаем над названиями переменных.

**Comment by antosha417** [comment]
нарисуй 1000 картошек

**Comment by Claptar** [comment]
@antosha417  Сделал 1000 картошечек. Над переменными и комментариями подумаю на выходных)
aeead89f830e7f99285dec9e28166f2b03fe9c08
56ce4b84d373db80f41f78c59c7d6b61b7f7cf11

**Comment by antosha417** [comment]
Не нужно каждый коммит сюда писать, пиши только когда хочешь следующую итерацию сдачи провести. Зачем мне это это смотреть, если не готово ещё?

**Comment by antosha417** [comment]
Почему сразу не писать цикл?

**Comment by Claptar** [comment]
@antosha417 
a4fdb1cfb01b865e138e515f30016c8aaf1fefce
Всмысле сразу написать цикл ?

**Comment by Claptar** [comment]
Файл Potato3 в graphics

**Comment by antosha417** [comment]
Почему ты для трёх повторений написал руками, а для 1000 цикл?

**Comment by antosha417** [comment]
Хороший ли это коммит?

**Comment by antosha417** [comment]
Закрывай

**Comment by Claptar** [comment]
@antosha417, я случайно:pensive:
