### ISSUE TITLE
Ball (Game, creating)

### ISSUE THREAD

**Issue by Claptar** [Claptar/prog_Binkevich#9]

**Comment by Claptar** [comment]
@antosha417

**Comment by antosha417** [comment]
Добавь хеш коммита к своему комментарию, я просил в телеграмме об этом, спасибо.

**Comment by Claptar** [comment]
04b1e2168260045256ded54a4ac6d8249bcde984
5d28b0d11a66c73cba59fefa5183dd5fed3a0d62
988c3c4f1e1240325067096b495587935c4c0690
592697708bf36982e1ec1ce46f677574c821cc30
d63809e3d3e25df4c40875d4ec58527051e4a252
a51ad344857e187e4525153472e4d1b37c1a6699
@antosha417

**Comment by antosha417** [comment]
Давай если я кликнул  счёт будет сразу же обновляться, а не с задержкой?

**Comment by antosha417** [comment]
Пайчарм же опечатки тоже подчёркивает, исправляй

**Comment by antosha417** [comment]
Почитай как в питоне возводить в квадрат

**Comment by antosha417** [comment]
Глобальные переменный называй БОЛЬШИМИ_БУКВАМИ

**Comment by antosha417** [comment]
Однобуквенные переменные плохо

**Comment by Claptar** [comment]
@antosha417 
e4e4d23aa53d7ff4f8859db689e225ab241ed90b
e510e7253cead46acec4614d24d96185c5b9dddc

**Comment by Claptar** [comment]
Файл Potato3 в graphics

**Comment by Claptar** [comment]
Файл Catch_a_ball в ball

**Comment by antosha417** [comment]
Почитай как в питоне возводить в квадрат

**Comment by antosha417** [comment]
Пайчарм ругается на твой кодстайл и несоблюдение пеп8, поправь, пожалуйста.

**Comment by antosha417** [comment]
Пока ставлю тебе 0,9  за задачу, чтобы поднять поправь код.

**Comment by Claptar** [comment]
@antosha417 
43a68c0601e046ff4e0ce27e841e5af5526c1abc

**Comment by Claptar** [comment]
@antosha417 Так я исправил, в самом комитете об этом написано. А, вспомнил, по-моему я делал поправку на контур, вроде, при построении шарика контур строится поверх исходного шарика и не учитывается в радиусе. Вроде я это проверял.

**Comment by antosha417** [comment]
Закрывай
